ONLY_CERN_SUBJECTS = [
    "Particle Physics - Experiment",
    "Particle Physics - Phenomenology",
    "Particle Physics - Theory",
    "Particle Physics - Lattice",
    "Nuclear Physics - Experiment",
    "Nuclear Physics - Theory",
    "General Relativity and Cosmology",
    "General Theoretical Physics",
    "Detectors and Experimental Techniques",
    "Accelerators and Storage Rings",
    "Health Physics and Radiation Effects",
    "Computing and Computers",
    "Mathematical Physics and Mathematics",
    "Astrophysics and Astronomy",
    "Nonlinear Systems",
    "Condensed Matter",
    "Other Fields of Physics",
    "Chemical Physics and Chemistry",
    "Engineering",
    "Information Transfer and Management",
    "Physics in General",
    "Commerce, Economics, Social Science",
    "Biography, Geography, History",
    "Other Subjects",
    "Science in General",
    "Quantum Technology",
    "Education and Outreach",
    "Popular Science",
]
